### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by willfurnell** [OfriMarx/pam_oauth#1]
Hey :) Do you have any docs for how I might be able to run this on my system please?

Thanks!

**Comment by OfriMarx** [comment]
Sure, what system are you using? This project was tested on Arch Linux but should run on all Linux distros and maybe on some other Unix based systems.

To be honest, I completely forgot about this project and haven't quite finished it yet. the OAUTH 2 server works well, though it does not implement the full protocol and is a bit different from the specifications in the RFC. also, the pam module doesn't do the authentication using the server. It currently uses a file which contains the usernames and passwords (/etc/pasten.conf - coded in line 54 if you want to change it).

I might consider finishing it and adding proper documentation, especially if you're interested. But this could take a couple of days, so I'll soon reply with instructions on how to run this current version. There is a README file with some instructions, but I'll try to elaborate more in a following comment.

**Comment by willfurnell** [comment]
Ah okay thank you for the information. I already have an OAuth2 server, but was looking for a PAM OAuth2 module - so I think this project probably wouldn't be suitable for me. Thanks for the reply though!

**Comment by OfriMarx** [comment]
As I said, I might finish writing the PAM module, so feel free to check again in a week or two. And seeing that you don't plan on using the current PAM module, I'll wait with the more detailed docs until I start working on this project again. And of course, you are welcome to expand my module to your needs :)
I hope I helped!
